
name: CD - Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Dev
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: read
      packages: write
      id-token: write # Required for Azure login

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RG_NAME }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Update Kustomization with new image tags
        run: |
          sed -i "s|tag: \"dev\"|tag: \"${{ github.sha }}\"|g" k8s/overlays/dev/values/frontend.yaml
          sed -i "s|repository: your-acr-name.azurecr.io/frontend|repository: ghcr.io/${{ github.repository }}/frontend|g" k8s/apps/frontend/values.yaml
          sed -i "s|tag: \"dev\"|tag: \"${{ github.sha }}\"|g" k8s/overlays/dev/values/backend.yaml
          sed -i "s|repository: your-acr-name.azurecr.io/backend|repository: ghcr.io/${{ github.repository }}/backend|g" k8s/apps/backend/values.yaml

      - name: Deploy to Kubernetes
        run: kubectl apply -k k8s/overlays/dev
