# Default values for frontend chart.
replicaCount: 1

image:
  repository: ghcr.io/dardanrs988/testtestmusic/frontend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
