global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    # Assuming your backend service will expose a /metrics endpoint
    # You will need to add a Prometheus client library to your backend (e.g., prometheus-fastapi-instrumentator)
    # The hostname 'backend' is used here as Docker Compose provides service discovery
    static_configs:
      - targets: ['backend:8000']
